<div style="display:none; margin: 0px auto;" class="html5gallery" data-skin="horizontal" data-carouselbgcolorstart="#423731" data-carouselbgcolorend="#362F2B" data-width="850" data-height="450" data-resizemode="fill" data-padding="5" data-thumbwidth="100" data-thumbheight="70" data-thumbgap="8">
  
	<!-- Add images to Gallery -->
	<a href="http://buildinternet.s3.amazonaws.com/projects/mosaic/yourather.jpg"><img src="http://buildinternet.s3.amazonaws.com/projects/mosaic/yourather.jpg" alt="Dit is een afbeelding. Het is een mooie afbeelding, vol met weelderige kleurtjes." /></a>
	<a href="https://www.google.be/images/srpr/logo4w.png"><img src="https://www.google.be/images/srpr/logo4w.png" alt="Google, je vriend door dik en dun." /></a>
  
	<!-- Add Youtube video to Gallery -->
	<a href="http://www.youtube.com/watch?v=96GqYvxPnGs"><img src="http://img.youtube.com/vi/96GqYvxPnGs/0.jpg" alt="Hier komt floris zijn geweldig youtube filmpje" /></a>

	<!-- Add Vimeo video to Gallery
	<a href="http://player.vimeo.com/video/1084537?title=0&amp;byline=0&amp;portrait=0"><img src="images/Big_Buck_Bunny.jpg" alt="Vimeo Video"></a> -->

</div>

<script src="/assets/html5gallery/html5gallery.js"></script>